<a href="https://colab.research.google.com/github/Shivakumar-DS/NPN/blob/master/MovieReview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
%tensorflow_version 2.x
import tensorflow_datasets as tfds
import tensorflow_hub as hub

In [2]:
tf.__version__

'2.2.0'

In [6]:
tfds.list_builders()

['abstract_reasoning',
 'aeslc',
 'aflw2k3d',
 'amazon_us_reviews',
 'arc',
 'bair_robot_pushing_small',
 'beans',
 'big_patent',
 'bigearthnet',
 'billsum',
 'binarized_mnist',
 'binary_alpha_digits',
 'c4',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cars196',
 'cassava',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'cfq',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_1',
 'cifar10_corrupted',
 'citrus_leaves',
 'cityscapes',
 'civil_comments',
 'clevr',
 'cmaterdb',
 'cnn_dailymail',
 'coco',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'cos_e',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'deep_weeds',
 'definite_pronoun_resolution',
 'diabetic_retinopathy_detection',
 'div2k',
 'dmlab',
 'downsampled_imagenet',
 'dsprites',
 'dtd',
 'duke_ultrasound',
 'dummy_dataset_shared_generator',
 'dummy_mnist',
 'emnist',
 'eraser_multi_rc',
 'esnli',
 'eurosat',
 'fashion_mnist',
 'flic',
 'flores',
 'food101',
 'gap',
 'gigaword',
 'glue',
 'gr

In [0]:
#Text Classification or Sentiment analysis
train_data, validation_data,test_data = tfds.load(name='imdb_reviews',
                                                    split=('train[:60%]', 'train[60%:]', 'test'),
                                                    as_supervised=True)

In [17]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [18]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [19]:
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:3])

<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ],
       [ 0.71152234, -0.6353217 ,  1.7385626 , -1.1168286 , -0.5451594 ,
        -1.1808156 ,  0.09504455,  1.4653089 ,  0.66059524,  0.79308075,
        -2.2268345 ,  0.07446612, -1.4075904 , -0.70645386, -1.907037  ,
         1.4419787 ,  1.9551861 , -0.42660055, -2.8022065 ,  0.43727064]],
      dtype=float32)>

In [0]:
#The above code took 3 reviews and converted to Vectors

In [23]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [25]:
model.fit(train_data.shuffle(10000).batch(512),
          epochs=20,
          validation_data=validation_data.batch(512),
          verbose=1)

Epoch 1/20
30/30 [==============================] - 3s 105ms/step - loss: 0.6873 - accuracy: 0.5048 - val_loss: 0.6822 - val_accuracy: 0.5156
Epoch 2/20
30/30 [==============================] - 3s 101ms/step - loss: 0.6744 - accuracy: 0.5612 - val_loss: 0.6674 - val_accuracy: 0.6098
Epoch 3/20
30/30 [==============================] - 3s 103ms/step - loss: 0.6606 - accuracy: 0.6261 - val_loss: 0.6561 - val_accuracy: 0.6553
Epoch 4/20
30/30 [==============================] - 3s 101ms/step - loss: 0.6491 - accuracy: 0.6694 - val_loss: 0.6455 - val_accuracy: 0.6841
Epoch 5/20
30/30 [==============================] - 3s 103ms/step - loss: 0.6375 - accuracy: 0.7020 - val_loss: 0.6342 - val_accuracy: 0.7133
Epoch 6/20
30/30 [==============================] - 3s 101ms/step - loss: 0.6250 - accuracy: 0.7368 - val_loss: 0.6224 - val_accuracy: 0.7530
Epoch 7/20
30/30 [==============================] - 3s 102ms/step - loss: 0.6110 - accuracy: 0.7767 - val_loss: 0.6103 - val_accuracy: 0.7793
Epoch 

In [26]:
#The prediction is close to zero , so negative review
model.predict(["This is the worst movie I have ever seen"])

array([[0.01982741]], dtype=float32)

In [39]:
#The prediction is close to one , so positive review
model.predict(["How can one make such a horrible film"])

array([[6.907712e-05]], dtype=float32)

In [36]:
#The prediction is close to one , so positive review
model.predict(["An Excellent movie that i enjoyed a lot",
              "Worst movie ever",
              "How can one make such a horrible film",
               "Horrible"])

array([[9.6286821e-01],
       [6.0288470e-02],
       [6.9077119e-05],
       [1.6554962e-01]], dtype=float32)