In [3]:
import pandas as pd

In [7]:
data1 = pd.DataFrame({'id':[1],'name':['a']},index=[0,1])

In [8]:
data1

id name
0   1    a
1   1    a

In [9]:
pd.DataFrame([[1,'a'],[2, 'b']], columns=['id','name'],index = [0,1])

id name
0   1    a
1   2    b

In [14]:
import numpy as np

In [10]:
list1=[1, 2, 3, 4, 5]

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])

In [17]:
arr1+10

array([11, 12, 13, 14, 15])

In [18]:
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [19]:
len(arr1)

5

In [20]:
type(arr1)

numpy.ndarray

In [21]:
type(arr1[0])

numpy.int32

In [22]:
arr1.dtype

dtype('int32')

In [23]:
arr1.ndim

1

In [24]:
arr1[-1]

5

In [25]:
arr1[:3]

array([1, 2, 3])

In [26]:
arr1[::-1]

array([5, 4, 3, 2, 1])

In [27]:
arr1[-1::-1]

array([5, 4, 3, 2, 1])

In [28]:
arr2 = np.array([1,2,'1'])

In [29]:
arr2

array(['1', '2', '1'], dtype='<U11')

In [38]:
list(range(0,20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [45]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [44]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [46]:
arr2 = [5,6,7,8,9]

In [47]:
arr1+arr2

array([ 6,  8, 10, 12, 14])

In [49]:
np.linspace(0,10,5)

array([ 0.,  5., 10., 15., 20.])

In [50]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [51]:
arr_mdim = np.array([[1, 2, 3, 4, 5], [6,7,8,9,10]])

In [52]:
arr_mdim

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
arr_mdim.shape

(2, 5)

In [54]:
arr_mdim.ndim

2

In [55]:
arr_mdim[:,2]

array([3, 8])

In [56]:
arr_mdim[1,2]

8

In [59]:
arr5 = np.arange(35)

In [60]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [62]:
arr5.shape=(5,7)

In [63]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [67]:
arr5.reshape(7,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [68]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [69]:
arr_resha = arr5.reshape(7,5)

In [70]:
arr_resha

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [74]:
arr10 = np.array([1, 2, 3, 4, 5, 6])

In [75]:
arr10.argmax()

5

In [77]:
arr10[arr10.argmax()]

6

In [78]:
arr10.max()

6

In [79]:
arr10.argmin()

0

In [80]:
arr10.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [82]:
arr10.append[arr5]

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [83]:
arr10[arr10>3]

array([4, 5, 6])

In [84]:
arr10[3]=10

In [85]:
arr10

array([ 1,  2,  3, 10,  5,  6])

In [86]:
np.where(arr10>5,50,0)

array([ 0,  0,  0, 50,  0, 50])

In [90]:
arr11 = np.arange(35)

In [92]:
arr11.shape=(7,5)

In [93]:
arr11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [96]:
np.mean(arr11,axis=0)

array([15., 16., 17., 18., 19.])

In [97]:
np.mean(arr11,axis=1)

array([ 2.,  7., 12., 17., 22., 27., 32.])

In [99]:
np.sum(arr11,axis=0)

array([105, 112, 119, 126, 133])

In [100]:
np.median(arr11,axis=0)

array([15., 16., 17., 18., 19.])

In [101]:
arr11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [103]:
arr11.astype('float')

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.]])

In [105]:
arr11.astype('int')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [106]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [108]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [109]:
np.random.randint(0, 5, size=20)

array([2, 0, 2, 4, 0, 0, 3, 0, 0, 0, 4, 1, 1, 1, 1, 4, 4, 4, 3, 0])

In [110]:
np.random.random(5)

array([0.50125159, 0.73074334, 0.78604346, 0.01632223, 0.6710133 ])

In [111]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [112]:
np.random.random(2, 6,5)

TypeError: random_sample() takes at most 1 positional argument (3 given)

In [113]:
np.random.rand(10)

array([0.90923092, 0.49733775, 0.54155414, 0.11884012, 0.32094951,
       0.65853184, 0.48598705, 0.02400917, 0.8691742 , 0.90339442])

In [114]:
np.sin(30)

-0.9880316240928618

In [115]:
np.cos(90)

-0.4480736161291701

In [116]:
np.tan(90)

-1.995200412208242

In [118]:
np.cos(45)

0.5253219888177297